export const CHANGE_CONTROL = 'CHANGE_CONTROL';

export const CHANGE_ACTIVE_INDEX = 'CHANGE_ACTIVE_INDEX';

export const CHANGE_ACTVIE_STAGE_INDEX = 'CHANGE_ACTVIE_STAGE_INDEX';

export const CREATE_NEW_STAGE = 'CREATE_NEW_STAGE';

export const DELETE_STAGE = 'DELETE_STAGE';

export const CREATE_CONTROL_OF_ACTIVE_STAGE = 'CREATE_CONTROL_OF_ACTIVE_STAGE';
