export const CHANGE_CONTROL = 'CHANGE_CONTROL';

export const CHANGE_ACTIVE_INDEX = 'CHANGE_ACTIVE_INDEX';

export const CHANGE_ACTVIE_STAGE_INDEX = 'CHANGE_ACTVIE_STAGE_INDEX';

export const CREATE_NEW_STAGE = 'CREATE_NEW_STAGE';

export const DELETE_STAGE = 'DELETE_STAGE';

export const CREATE_CONTROL_OF_ACTIVE_STAGE = 'CREATE_CONTROL_OF_ACTIVE_STAGE';

export const SET_NEW_TEMPLATE = 'SET_NEW_TEMPLATE';

export const CHANGE_CURRENT_TIME = 'CHANGE_CURRENT_TIME';

export const TOGGLE_PLAY_STATE = 'TOGGLE_PLAY_STATE';

export const DELTETE_CONTROL = 'DELTETE_CONTROL';

export const CHANGE_CONTRL_ZINDEX = 'CHANGE_CONTRL_ZINDEX';

export const CHANGE_ACTIVE_STAGE_NAME = 'CHANGE_ACTIVE_STAGE_NAME';

export const CHANGE_ACTIVE_STAGE_POST = 'CHANGE_ACTIVE_STAGE_POST';

export const CHANGE_SCALE_CANVAS = 'CHANGE_SCALE_CANVAS';

export const CREATE_ANIMATE = 'CREATE_ANIMATE';

export const SELECT_ANIMATE_ID = 'SELECT_ANIMATE_ID';

export const CREATE_EVENT = 'CREATE_EVENT';

export const SELECT_EVENT_ID = 'SELECT_EVENT_ID';

export const CHANGE_NAME = 'CHANGE_NAME';

export const RESET_PROJECT = 'RESET_PROJECT';

export const SET_COMPONENT_LIST = 'SET_COMPONENT_LIST';
